Update navbar and logo with new design
guyboireau/BioDesignLabFront pull request #12
Opened 2024-01-24 14:34 UTC by BastienBenech

2024-01-24 14:59 UTC, sophie-pan requested changes

2024-01-24 14:59 UTC, sophie-pan commented on src/app/components/navigation/navbar/index.tsx
> +                <Link href="/librairy" className="group">
```suggestion
                <Link href="/library" className="group">
```

2024-01-24 14:59 UTC, sophie-pan commented on src/app/components/navigation/navbar/index.tsx
> +                  </svg>
fais-en un composant

2024-02-07 08:27 UTC, guyboireau submitted a review, later dismissed

2024-02-07 09:28 UTC, guyboireau submitted a review, later dismissed

2024-02-07 09:31 UTC, sophie-pan approved these changes

2024-02-07 09:36 UTC, merged